# Page admin routing
monsieurbiz_sylius_cms_page_admin:
    resource: |
        alias: monsieurbiz_cms_page.page
        section: admin
        permission: true
        templates: "@SyliusAdmin\\shared\\crud"
        except: ['show']
        redirect: update
        grid: monsieurbiz_cms_page
    type: sylius.resource

# Page preview
monsieurbiz_cms_page_admin_page_preview:
    path: /page/preview/{id}
    defaults:
        _controller: monsieurbiz_cms_page.controller.page::previewAction
        template: '@MonsieurBizSyliusCmsPagePlugin\admin\page\preview.html.twig'
        _sylius:
            section: shop
