services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusCmsPagePlugin\:
        resource: '../../*'
        exclude: '../../{Component}'

    MonsieurBiz\SyliusCmsPagePlugin\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
    
    # Let's try to find the locale one more time!
    MonsieurBiz\SyliusCmsPagePlugin\Context\LastChanceLocaleContext:
        tags:
            - { name: sylius.context.locale, priority: -127 }

    # Menu item in admin panel
    MonsieurBiz\SyliusCmsPagePlugin\Listener\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItem }

    # Page Forms
    MonsieurBiz\SyliusCmsPagePlugin\Form\Type\PageType:
        arguments:
            $dataClass: '%monsieurbiz_cms_page.model.page.class%'
            $validationGroups: ['monsieurbiz']
    MonsieurBiz\SyliusCmsPagePlugin\Form\Type\PageTranslationType:
        arguments:
            $dataClass: '%monsieurbiz_cms_page.model.page_translation.class%'
            $validationGroups: ['monsieurbiz']

    # Routing Context
    MonsieurBiz\SyliusCmsPagePlugin\Routing\RequestContext:
        decorates: router.request_context
        arguments: ['@MonsieurBiz\SyliusCmsPagePlugin\Routing\RequestContext.inner']

    monsieurbiz.cms_page.datetime_provider:
        class: Symfony\Component\Clock\Clock
        public: true

    # Live components
    sylius_admin.monsieurbiz_cms_page.twig.component.page.form:
        autoconfigure: false
        class: MonsieurBiz\SyliusCmsPagePlugin\Component\PageFormComponent
        arguments:
            - '@monsieurbiz_cms_page.repository.page'
            - '@form.factory'
            - '%monsieurbiz_cms_page.model.page.class%'
            - 'MonsieurBiz\SyliusCmsPagePlugin\Form\Type\PageType'
        tags:
            - { name: 'sylius.live_component.admin', key: 'sylius_admin:monsieurbiz_cms_page:page:form' }
